CREATE TABLE "PERSON" (
 id INT NOT NULL PRIMARY KEY,
 name VARCHAR2(255),
 age INT NOT NULL
);

INSERT INTO PERSON VALUES (1, 'John', 17);
INSERT INTO PERSON VALUES (2, 'Simon', 25);
INSERT INTO PERSON VALUES (3, 'Anabelle', 19);